services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=url_shortener'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '32678:5432'
